package view;

import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.TextElementArray;
import controller.ControllerClientes;
import controller.ControllerEstoque;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelClientes;
import model.ModelEstoque;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileOutputStream;

/**
 *
 * @author icant
 */
public class ViewVendas extends javax.swing.JFrame {

    // INSTÂNCIAR OBJETOS //
    ModelClientes modelClientes = new ModelClientes();
    ControllerClientes controllerClientes = new ControllerClientes();
    List<ModelClientes> listaClientes = new ArrayList<>();
    ModelEstoque modelEstoque = new ModelEstoque();
    ControllerEstoque controllerEstoque = new ControllerEstoque();
    ArrayList<ModelEstoque> listaProdutos = new ArrayList<>();

    /**
     * Creates new form ViewVendas
     */
    public ViewVendas() {
        initComponents();
        setLocationRelativeTo(null);
        listarProdutos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jBPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTClientes = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jBAddProduto = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTCarrinho = new javax.swing.JTable();
        jBRemover = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCProdutos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jBFinalizar = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jTCliCPF = new javax.swing.JFormattedTextField();
        jSQtd = new javax.swing.JSpinner();
        jFCodProd = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jTTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharma");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gervendas.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N
        jLabel2.setText(" CPF:");

        jBPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        jBPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        jBPesquisa.setBorderPainted(false);
        jBPesquisa.setContentAreaFilled(false);
        jBPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisaActionPerformed(evt);
            }
        });

        jTClientes.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Rua", "Bairro", "Contato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTClientes.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTClientes);

        jLabel4.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/produtos.png"))); // NOI18N
        jLabel4.setText(" Produtos:");

        jBAddProduto.setBackground(new java.awt.Color(255, 255, 255));
        jBAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jBAddProduto.setBorderPainted(false);
        jBAddProduto.setContentAreaFilled(false);
        jBAddProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddProdutoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrinho.png"))); // NOI18N
        jLabel6.setText(" Carrinho");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTCarrinho.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.", "Descrição do Produto", "Qtd.", "R$ Unid.", "R$ Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCarrinho.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(jTCarrinho);
        if (jTCarrinho.getColumnModel().getColumnCount() > 0) {
            jTCarrinho.getColumnModel().getColumn(0).setMinWidth(40);
            jTCarrinho.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTCarrinho.getColumnModel().getColumn(0).setMaxWidth(40);
            jTCarrinho.getColumnModel().getColumn(2).setMinWidth(35);
            jTCarrinho.getColumnModel().getColumn(2).setPreferredWidth(35);
            jTCarrinho.getColumnModel().getColumn(2).setMaxWidth(35);
            jTCarrinho.getColumnModel().getColumn(3).setMinWidth(60);
            jTCarrinho.getColumnModel().getColumn(3).setPreferredWidth(60);
            jTCarrinho.getColumnModel().getColumn(3).setMaxWidth(60);
            jTCarrinho.getColumnModel().getColumn(4).setMinWidth(60);
            jTCarrinho.getColumnModel().getColumn(4).setPreferredWidth(60);
            jTCarrinho.getColumnModel().getColumn(4).setMaxWidth(60);
        }

        jBRemover.setBackground(new java.awt.Color(255, 255, 255));
        jBRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menos-30.png"))); // NOI18N
        jBRemover.setBorderPainted(false);
        jBRemover.setContentAreaFilled(false);
        jBRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quantidade.png"))); // NOI18N
        jLabel3.setText("Qtd.:");

        jCProdutos.setEditable(true);
        jCProdutos.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jCProdutosPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel5.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/total.png"))); // NOI18N
        jLabel5.setText("Total:");

        jBFinalizar.setBackground(new java.awt.Color(255, 255, 255));
        jBFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finalizar.png"))); // NOI18N
        jBFinalizar.setBorderPainted(false);
        jBFinalizar.setContentAreaFilled(false);
        jBFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarActionPerformed(evt);
            }
        });

        jBVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltar.png"))); // NOI18N
        jBVoltar.setBorderPainted(false);
        jBVoltar.setContentAreaFilled(false);
        jBVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        try {
            jTCliCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jSQtd.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));

        jFCodProd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFCodProd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFCodProdFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        jLabel7.setText("Cód:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(0, 122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jBAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTCliCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBPesquisa)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTCliCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jSQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jCProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBAddProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6))
                    .addComponent(jBFinalizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBRemover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFCodProdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFCodProdFocusLost
        modelEstoque = controllerEstoque.getEstoqueController(Integer.parseInt(jFCodProd.getText().replaceAll(" ", "")));
        jCProdutos.setSelectedItem(modelEstoque.getProdDescricao());
    }//GEN-LAST:event_jFCodProdFocusLost

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        setVisible(false);
        new ViewMenuPrincipal().setVisible(true);
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisaActionPerformed
        modelClientes = controllerClientes.getClientesController(Long.parseLong(jTCliCPF.getText().replaceAll("\\.", "").replaceAll("-", "")));
        DefaultTableModel modelo = (DefaultTableModel) jTClientes.getModel();
        modelo.setNumRows(0);
        modelo.addRow(new Object[]{
            modelClientes.getCliCPF(),
            modelClientes.getCliNome(),
            modelClientes.getCliEndereco(),
            modelClientes.getCliBairro(),
            modelClientes.getCliContato()
        });
    }//GEN-LAST:event_jBPesquisaActionPerformed

    private void jBAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddProdutoActionPerformed
        if (jCProdutos.getSelectedItem().equals("")) {
           JOptionPane.showMessageDialog(this, "Erro! Selecione um produto.");
        } else {
            modelEstoque = controllerEstoque.getEstoqueController(Integer.parseInt(jFCodProd.getText()));
            DefaultTableModel modelo = (DefaultTableModel) jTCarrinho.getModel();
            int cont = 0;
            double qtd = 0;
            qtd = Double.parseDouble(jSQtd.getValue().toString());
            for (int i = 0; i < cont; i++) {
                modelo.setNumRows(0);
            }
            modelo.addRow(new Object[]{
                modelEstoque.getProdId(),
                modelEstoque.getProdDescricao(),
                jSQtd.getValue(),
                modelEstoque.getProdPreco(),
                qtd * modelEstoque.getProdPreco()
            });
            somarTotal();
        }

    }//GEN-LAST:event_jBAddProdutoActionPerformed

    private void jBFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarActionPerformed
        int linhacli = jTClientes.getSelectedRow();
        if (linhacli < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente!");
        } else {
            JOptionPane.showMessageDialog(this, "Pedido salvo com sucesso!");
            gerarPdf();
        }
    }//GEN-LAST:event_jBFinalizarActionPerformed

    private void jCProdutosPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCProdutosPopupMenuWillBecomeInvisible
        modelEstoque = controllerEstoque.getEstoqueController(jCProdutos.getSelectedItem().toString());
        jFCodProd.setText(String.valueOf(modelEstoque.getProdId()));

    }//GEN-LAST:event_jCProdutosPopupMenuWillBecomeInvisible

    private void jBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverActionPerformed
        int linha = jTCarrinho.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) jTCarrinho.getModel();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um produto primeiro!");
        } else {
            modelo.removeRow(jTCarrinho.getSelectedRow());
            jTCarrinho.setModel(modelo);
            somarTotal();

        }
    }//GEN-LAST:event_jBRemoverActionPerformed

    private void listarProdutos() {
        listaProdutos = controllerEstoque.getListaEstoqueController();
        jCProdutos.removeAllItems();
        for (int i = 0; i < listaProdutos.size(); i++) {
            jCProdutos.addItem(listaProdutos.get(i).getProdDescricao());
        }
    }

    private void somarTotal() {
        double soma = 0, preco;
        int cont = jTCarrinho.getRowCount();
        for (int i = 0; i < cont; i++) {
            preco = (double) jTCarrinho.getValueAt(i, 4);
            soma = soma + preco;

        }
        jTTotal.setText(String.valueOf(soma).format("%.2f",soma));
        //jTTotal.setText(String.valueOf(soma%.2f));
    }

    private void gerarPdf() {
        Document documento = new Document();
        int linha = 0;
        int tamanhoCarrinho = jTCarrinho.getRowCount();
        String nome = (String) jTClientes.getValueAt(0, 1);
        String endereco = (String) jTClientes.getValueAt(0, 2);
        String bairro = (String) jTClientes.getValueAt(0, 3);
        String contato = (String) jTClientes.getValueAt(0, 4);
        String total = (String) jTTotal.getText();

        try {
            String caminho = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(caminho + "/desktop/Pharma.pdf"));
            documento.open();
            //Font font = new Font();
            documento.add(new Paragraph("=== DADOS DA ENTREGA ==="));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("Cliente: " + nome));
            documento.add(new Paragraph("Endereço: " + endereco));
            documento.add(new Paragraph("Bairro: " + bairro));
            documento.add(new Paragraph("Contato: " + contato));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("========================"));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("=== LISTA DE PRODUTOS ==="));
            documento.add(new Paragraph(" "));
            for (int i = 0; i < tamanhoCarrinho; i++) {
                String produto = (String) jTCarrinho.getValueAt(linha, 1);
                String qtd = (String) jTCarrinho.getValueAt(linha, 2).toString();
                String precouni = (String) jTCarrinho.getValueAt(linha, 3).toString();
                documento.add(new Paragraph(qtd + "x - " + produto + " - R$ " + precouni + " /unid."));
                linha++;
            }
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("=== TOTAL: R$"+ total +" ==="));
            documento.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao gerar PDF.");

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddProduto;
    private javax.swing.JButton jBFinalizar;
    private javax.swing.JButton jBPesquisa;
    private javax.swing.JButton jBRemover;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JComboBox<String> jCProdutos;
    private javax.swing.JFormattedTextField jFCodProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSQtd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTCarrinho;
    private javax.swing.JFormattedTextField jTCliCPF;
    private javax.swing.JTable jTClientes;
    private javax.swing.JTextField jTTotal;
    // End of variables declaration//GEN-END:variables
}
